// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBookApi2.Data;

#nullable disable

namespace MyBookApi2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623120724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyBookApi2.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Software engineer known as Uncle Bob, author of Clean Code",
                            Name = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Software engineer, author and speaker on software design",
                            Name = "Martin Fowler"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Programmer and co-author of The Pragmatic Programmer",
                            Name = "Andrew Hunt"
                        });
                });

            modelBuilder.Entity("MyBookApi2.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Price = 34.99m,
                            PublishedDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Price = 39.99m,
                            PublishedDate = new DateTime(2017, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Price = 29.99m,
                            PublishedDate = new DateTime(2011, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Clean Coder"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Price = 44.99m,
                            PublishedDate = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Price = 49.99m,
                            PublishedDate = new DateTime(2002, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Price = 39.99m,
                            PublishedDate = new DateTime(1996, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Analysis Patterns"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Price = 49.99m,
                            PublishedDate = new DateTime(1999, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Price = 34.99m,
                            PublishedDate = new DateTime(2007, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pragmatic Unit Testing in C# with NUnit"
                        });
                });

            modelBuilder.Entity("MyBookApi2.Models.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 4
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 7,
                            TagId = 1
                        });
                });

            modelBuilder.Entity("MyBookApi2.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Software Design"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Refactoring"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Best Practices"
                        });
                });

            modelBuilder.Entity("MyBookApi2.Models.Book", b =>
                {
                    b.HasOne("MyBookApi2.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MyBookApi2.Models.BookTag", b =>
                {
                    b.HasOne("MyBookApi2.Models.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBookApi2.Models.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyBookApi2.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MyBookApi2.Models.Book", b =>
                {
                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("MyBookApi2.Models.Tag", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
